version: '3'
services: 
    salserver:
        build: 
            context: .
        container_name: nginx_container
        ports: 
            - 80:80
        networks: 
            - default
            - sample_network
networks: 
    sample_network:
        external: true
